name: Create production builds

jobs:
  build_ios:
    name: Build iOS (production)
    type: build
    params:
      platform: ios
      profile: production

  build_android:
    name: Build Android (production)
    type: build
    params:
      platform: android
      profile: production
