/**
 * Generates the combined local+remote daily notification timeline for
 * three personas by calling the REAL reminder-generation and
 * ownership/budget functions this app runs in production — not
 * hand-written examples. Run with: node scripts/generateNotificationTimelines.mjs
 *
 * LOCAL portion is the fixed, verified output of LOCAL_ALLOCATION
 * (mobile/services/pushNotifications.js) — hydration 10:00/15:00, food
 * 12:00, activity 16:00, mood 20:00, streak 21:00 — confirmed by
 * __tests__/notifications/pushNotificationsScheduling.test.js's real
 * scheduling assertions against a fake Notifications client (this script
 * can't import React-Native mobile code directly, so the local side is
 * cited from that test's actual output rather than re-simulated here).
 *
 * REMOTE portion is generated by actually calling generateHydrationReminders/
 * generateFoodReminders/generateMoodReminders/generateActivityReminders/
 * generateMotivationReminders across all 24 hours, then applying the real
 * filterRemindersForDevice (ownership exclusivity) and getEffectiveDailyCap
 * (budget) — the same functions smartReminderJob.js calls in production.
 */
import {
  generateHydrationReminders,
  generateFoodReminders,
  generateMoodReminders,
  generateActivityReminders,
  generateMotivationReminders,
} from '../src/services/smartReminderService.js';
import { filterRemindersForDevice, getEffectiveDailyCap, LOCAL_ALLOCATION } from '../src/utils/notificationOwnership.js';
import { NOTIFICATION_POLICY } from '../src/utils/notificationPolicy.js';

const LOCAL_SCHEDULE = [
  { type: 'hydration_nudge', hours: [10, 15] },
  { type: 'daily_reminder', hours: [12] },
  { type: 'activity_reminder', hours: [16] },
  { type: 'mood_checkin', hours: [20] },
  { type: 'streak_at_risk', hours: [21] },
];

function categoryForType(type) {
  if (type.includes('hydration')) return 'hydration_nudge';
  if (type.includes('food')) return 'daily_reminder';
  if (type.includes('mood')) return 'mood_checkin';
  if (type.includes('activity')) return 'activity_reminder';
  if (type === 'streak_at_risk') return 'streak_at_risk';
  return 'enabled'; // comeback, weekly_summary, etc.
}

function runPersona(name, { todayStats, goals, gamification, patterns, ownedCategories }) {
  console.log(`\n${'='.repeat(70)}\n${name}\n${'='.repeat(70)}`);

  console.log('\n-- LOCAL (scheduled allocation, fixed OS triggers, fires with zero connectivity) --');
  for (const { type, hours } of LOCAL_SCHEDULE) {
    if (!ownedCategories.has(type)) continue;
    console.log(`  ${type.padEnd(18)} ${hours.map((h) => `${String(h).padStart(2, '0')}:00`).join(', ')}`);
  }
  const localTotal = [...ownedCategories].reduce((sum, c) => sum + (LOCAL_ALLOCATION[c] || 0), 0);
  console.log(`  local total: ${localTotal}/day`);

  console.log('\n-- REMOTE candidates across 24h (generated by the real smartReminderService functions) --');
  const allCandidatesByHour = [];
  for (let hour = 0; hour < 24; hour++) {
    const context = { currentHour: hour, todayStats, goals, gamification, patterns };
    const raw = [
      ...generateHydrationReminders(context),
      ...generateFoodReminders(context),
      ...generateMoodReminders(context),
      ...generateActivityReminders(context),
      ...generateMotivationReminders(context),
    ];
    const afterOwnership = filterRemindersForDevice(raw, ownedCategories, categoryForType);
    if (afterOwnership.length > 0) {
      allCandidatesByHour.push({ hour, candidates: afterOwnership });
    }
  }

  const effectiveCap = getEffectiveDailyCap(NOTIFICATION_POLICY.MAX_NOTIFICATIONS_PER_USER_PER_DAY, ownedCategories);
  console.log(`  effective backend daily cap for this device: ${effectiveCap}`);

  let remoteSentCount = 0;
  let lastSentHour = -100;
  for (const { hour, candidates } of allCandidatesByHour) {
    const top = candidates[0]; // highest priority (smartReminderJob sends candidates[0] per tick)
    const spacingOk = (hour - lastSentHour) >= 1; // 60-min floor, hour-granular here
    const capOk = remoteSentCount < effectiveCap;
    const willSend = spacingOk && capOk;
    console.log(
      `  ${String(hour).padStart(2, '0')}:00  candidates=[${candidates.map((c) => c.type).join(', ')}]` +
      `  -> ${willSend ? `SENT: ${top.type}` : `held (${!capOk ? 'daily_cap' : 'min_spacing'})`}`
    );
    if (willSend) {
      remoteSentCount++;
      lastSentHour = hour;
    }
  }
  console.log(`  remote total actually sent: ${remoteSentCount}/day (cap was ${effectiveCap})`);
  console.log(`\n  COMBINED TOTAL (local + remote): ${localTotal + remoteSentCount}/day`);
}

const ALL_OWNED = new Set(Object.keys(LOCAL_ALLOCATION));

const MEAL_TIMES = { breakfast: { hour: 8 }, lunch: { hour: 12 }, dinner: { hour: 18 } };

// New user, day 1: goals set, no logs yet today, no streak, no history, and
// critically engagementLevel: 'new' — generateMoodReminders/generateActivityReminders
// both explicitly suppress themselves for a brand-new, not-yet-engaged user
// (real behavior in the actual code, not an artifact of this script).
runPersona('NEW USER (day 1, all local categories owned)', {
  todayStats: {
    water: { totalLiters: 0, totalLogs: 0 },
    food: { totalMeals: 0, mealTypes: {} },
    mood: { totalLogs: 0 },
    activity: { steps: 0, totalLogs: 0, sedentaryHours: 0 },
  },
  goals: { waterLiters: 2.5, dailyCalories: 2000, stepGoal: 10000 },
  gamification: { streak: 0, lastLogDate: null, timezoneOffset: 0 },
  patterns: { engagementLevel: 'new', mealTimes: MEAL_TIMES, patterns: { mood: { peakHours: [] } } },
  ownedCategories: ALL_OWNED,
});

// Active user: healthy streak, hasn't logged yet today (so evening
// categories are still live candidates), goals not yet met, fully engaged.
runPersona('ACTIVE USER (weeks in, streak=6, no logs yet today)', {
  todayStats: {
    water: { totalLiters: 0.3, totalLogs: 1 },
    food: { totalMeals: 0, mealTypes: {} },
    mood: { totalLogs: 0 },
    activity: { steps: 800, totalLogs: 1, sedentaryHours: 2 },
  },
  goals: { waterLiters: 2.5, dailyCalories: 2000, stepGoal: 10000 },
  gamification: { streak: 6, lastLogDate: new Date(), timezoneOffset: 0 },
  patterns: { engagementLevel: 'active', mealTimes: MEAL_TIMES, patterns: { mood: { peakHours: [20] } } },
  ownedCategories: ALL_OWNED,
});

// Inactive user: 4 days since last log, streak long since broken (0).
const fourDaysAgo = new Date(Date.now() - 4 * 24 * 60 * 60 * 1000);
runPersona('INACTIVE USER (4 days since last log, streak broken, full local ownership)', {
  todayStats: {
    water: { totalLiters: 0, totalLogs: 0 },
    food: { totalMeals: 0, mealTypes: {} },
    mood: { totalLogs: 0 },
    activity: { steps: 0, totalLogs: 0, sedentaryHours: 0 },
  },
  goals: { waterLiters: 2.5, dailyCalories: 2000, stepGoal: 10000 },
  gamification: { streak: 0, lastLogDate: fourDaysAgo, timezoneOffset: 0 },
  patterns: { engagementLevel: 'active', mealTimes: MEAL_TIMES, patterns: { mood: { peakHours: [20] } } },
  ownedCategories: ALL_OWNED,
});

// Same inactive user, but BEFORE local scheduling ever registered ownership
// (fresh install that hasn't foregrounded yet, or local scheduling failed) —
// shows the case where comeback messaging actually reaches the user,
// since nothing local is claiming any of the budget.
runPersona('INACTIVE USER, NO LOCAL OWNERSHIP REGISTERED YET (backend covers everything)', {
  todayStats: {
    water: { totalLiters: 0, totalLogs: 0 },
    food: { totalMeals: 0, mealTypes: {} },
    mood: { totalLogs: 0 },
    activity: { steps: 0, totalLogs: 0, sedentaryHours: 0 },
  },
  goals: { waterLiters: 2.5, dailyCalories: 2000, stepGoal: 10000 },
  gamification: { streak: 0, lastLogDate: fourDaysAgo, timezoneOffset: 0 },
  patterns: { engagementLevel: 'active', mealTimes: MEAL_TIMES, patterns: { mood: { peakHours: [20] } } },
  ownedCategories: new Set(),
});
