/**
 * Exercise Database
 *
 * Gym-floor coverage comparable to mainstream fitness apps: machines, free
 * weights, cables, bodyweight, functional and cardio equipment, on top of the
 * original sport/cardio list.
 *
 * Each entry carries:
 * - `category`    modality chip shown in the Categories row
 * - `muscleGroup` Upper Body / Lower Body / Core / Full Body (Focus row)
 * - `equipment`   what you need to perform it (also powers the Machines focus)
 * - `met`         Metabolic Equivalent of Task (Compendium of Physical Activities)
 * - `apiType`     backend activity type used for MET-based calorie logging
 * - `aliases`     extra search terms (gym slang, machine brand names, muscles)
 *
 * `caloriesPer30Min` is derived from `met` for a 70kg (154lb) person so the
 * card estimate and the MET formula never drift apart.
 */

export const EXERCISE_CATEGORIES = {
  CARDIO: 'Cardio',
  STRENGTH: 'Strength',
  YOGA: 'Yoga',
  SPORTS: 'Sports',
  WALKING: 'Walking',
  CYCLING: 'Cycling',
  SWIMMING: 'Swimming',
  FLEXIBILITY: 'Flexibility',
};

export const MUSCLE_GROUPS = {
  UPPER_BODY: 'Upper Body',
  LOWER_BODY: 'Lower Body',
  CORE: 'Core',
  FULL_BODY: 'Full Body',
};

export const EQUIPMENT = {
  MACHINE: 'Machine',
  CABLE: 'Cable',
  SMITH: 'Smith Machine',
  CARDIO_MACHINE: 'Cardio Machine',
  BARBELL: 'Barbell',
  DUMBBELL: 'Dumbbell',
  KETTLEBELL: 'Kettlebell',
  BODYWEIGHT: 'Bodyweight',
  OTHER: 'Other',
};

/** Equipment that counts as "Machines" in the Focus filter */
const MACHINE_EQUIPMENT = new Set([
  EQUIPMENT.MACHINE,
  EQUIPMENT.CABLE,
  EQUIPMENT.SMITH,
  EQUIPMENT.CARDIO_MACHINE,
]);

/**
 * Intensity levels. Keys mirror the backend's light/moderate/vigorous buckets
 * so the previewed estimate and the calories the API logs stay in step.
 */
export const INTENSITY_LEVELS = {
  LIGHT: { label: 'Light', multiplier: 0.7, color: '#10B981' },
  MODERATE: { label: 'Moderate', multiplier: 1.0, color: '#F59E0B' },
  VIGOROUS: { label: 'Vigorous', multiplier: 1.3, color: '#EF4444' },
};

/**
 * Rows logged before the picker matched the backend's buckets still hold
 * 'low' / 'high' / 'very_high'. Map them rather than silently showing every
 * historic activity as "Moderate".
 */
const LEGACY_INTENSITY_KEYS = {
  LOW: 'LIGHT',
  HIGH: 'VIGOROUS',
  VERY_HIGH: 'VIGOROUS',
};

/**
 * Resolve any stored intensity value to a level, old or new.
 * @param {string} value - e.g. 'moderate', 'very_high', 'VIGOROUS'
 */
export const resolveIntensity = (value) => {
  const key = String(value || '').toUpperCase();
  return INTENSITY_LEVELS[key] || INTENSITY_LEVELS[LEGACY_INTENSITY_KEYS[key]] || INTENSITY_LEVELS.MODERATE;
};

const { CARDIO, STRENGTH, YOGA, SPORTS, WALKING, CYCLING, SWIMMING, FLEXIBILITY } = EXERCISE_CATEGORIES;
const { UPPER_BODY, LOWER_BODY, CORE, FULL_BODY } = MUSCLE_GROUPS;

const RAW_EXERCISES = [
  // ==========================================================================
  // CARDIO — MACHINES & CLASSIC
  // ==========================================================================
  {
    id: 'running',
    name: 'Running',
    category: CARDIO,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'walk',
    description: 'Outdoor running, 6-7 mph',
    met: 10.0,
    apiType: 'running',
    aliases: ['run', 'sprint', 'road run'],
  },
  {
    id: 'jogging',
    name: 'Jogging',
    category: CARDIO,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'walk',
    description: 'Light to moderate pace jogging',
    met: 7.0,
    apiType: 'running',
    aliases: ['jog', 'easy run'],
  },
  {
    id: 'treadmill-walk',
    name: 'Treadmill Walking',
    category: CARDIO,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.CARDIO_MACHINE,
    icon: 'walk',
    description: 'Flat treadmill walk, 3-3.5 mph',
    met: 3.5,
    apiType: 'walking',
    aliases: ['treadmill', 'tread mill', 'walking machine'],
  },
  {
    id: 'treadmill-incline',
    name: 'Incline Treadmill Walk',
    category: CARDIO,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.CARDIO_MACHINE,
    icon: 'trending-up',
    description: 'Uphill treadmill walk, 10-15% grade',
    met: 6.0,
    apiType: 'walking',
    aliases: ['treadmill', 'incline walk', '12-3-30', 'hill walk'],
  },
  {
    id: 'treadmill-run',
    name: 'Treadmill Running',
    category: CARDIO,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.CARDIO_MACHINE,
    icon: 'walk',
    description: 'Treadmill run, 6-7 mph',
    met: 10.0,
    apiType: 'running',
    aliases: ['treadmill', 'tread mill', 'indoor run'],
  },
  {
    id: 'elliptical',
    name: 'Elliptical',
    category: CARDIO,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.CARDIO_MACHINE,
    icon: 'analytics',
    description: 'Elliptical cross-trainer, moderate effort',
    met: 8.0,
    apiType: 'cardio',
    aliases: ['cross trainer', 'x trainer'],
  },
  {
    id: 'arc-trainer',
    name: 'Arc Trainer',
    category: CARDIO,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.CARDIO_MACHINE,
    icon: 'analytics',
    description: 'Low-impact stride machine',
    met: 7.0,
    apiType: 'cardio',
    aliases: ['cybex arc', 'glider'],
  },
  {
    id: 'stair-climbing',
    name: 'Stair Climber',
    category: CARDIO,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.CARDIO_MACHINE,
    icon: 'trending-up',
    description: 'StairMaster or stepmill',
    met: 9.0,
    apiType: 'cardio',
    aliases: ['stairmaster', 'stepmill', 'stair master', 'steps', 'jacobs ladder'],
  },
  {
    id: 'rowing',
    name: 'Rowing Machine',
    category: CARDIO,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.CARDIO_MACHINE,
    icon: 'boat',
    description: 'Indoor rower, moderate pace',
    met: 8.5,
    apiType: 'cardio',
    aliases: ['erg', 'rower', 'concept 2', 'row'],
  },
  {
    id: 'ski-erg',
    name: 'Ski Erg',
    category: CARDIO,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.CARDIO_MACHINE,
    icon: 'pulse',
    description: 'Standing pull-down ski trainer',
    met: 7.0,
    apiType: 'cardio',
    aliases: ['skierg', 'ski machine'],
  },
  {
    id: 'air-bike',
    name: 'Air Bike',
    category: CARDIO,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.CARDIO_MACHINE,
    icon: 'bicycle',
    description: 'Fan bike with moving handles',
    met: 9.0,
    apiType: 'cardio',
    aliases: ['assault bike', 'echo bike', 'fan bike'],
  },
  {
    id: 'hiit',
    name: 'HIIT Training',
    category: CARDIO,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'flash',
    description: 'High-intensity interval training',
    met: 8.0,
    apiType: 'hiit',
    aliases: ['intervals', 'tabata', 'metcon'],
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    category: CARDIO,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'fitness',
    description: 'Skipping rope cardio',
    met: 11.0,
    apiType: 'hiit',
    aliases: ['skipping', 'skip rope', 'double unders'],
  },

  // ==========================================================================
  // STRENGTH — CHEST (UPPER BODY PUSH)
  // ==========================================================================
  {
    id: 'bench-press',
    name: 'Barbell Bench Press',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'barbell',
    description: 'Flat bench press for chest and triceps',
    met: 5.0,
    apiType: 'strength',
    aliases: ['bench', 'flat bench', 'chest', 'pecs'],
  },
  {
    id: 'incline-bench-press',
    name: 'Incline Bench Press',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'barbell',
    description: 'Inclined barbell press for upper chest',
    met: 5.0,
    apiType: 'strength',
    aliases: ['incline bench', 'upper chest'],
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.DUMBBELL,
    icon: 'barbell',
    description: 'Flat dumbbell press for chest',
    met: 5.0,
    apiType: 'strength',
    aliases: ['db bench', 'dumbell press', 'chest'],
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.DUMBBELL,
    icon: 'barbell',
    description: 'Inclined dumbbell press for upper chest',
    met: 5.0,
    apiType: 'strength',
    aliases: ['incline db press', 'upper chest'],
  },
  {
    id: 'chest-press-machine',
    name: 'Chest Press Machine',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Seated machine press for chest',
    met: 4.5,
    apiType: 'strength',
    aliases: ['seated chest press', 'machine press', 'chest', 'pecs'],
  },
  {
    id: 'incline-chest-press-machine',
    name: 'Incline Chest Press Machine',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Machine press angled for upper chest',
    met: 4.5,
    apiType: 'strength',
    aliases: ['incline machine press', 'upper chest'],
  },
  {
    id: 'smith-bench-press',
    name: 'Smith Machine Bench Press',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.SMITH,
    icon: 'barbell',
    description: 'Guided bar bench press',
    met: 4.5,
    apiType: 'strength',
    aliases: ['smith bench', 'smith press'],
  },
  {
    id: 'pec-deck',
    name: 'Pec Deck (Chest Fly)',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Seated fly machine for chest',
    met: 4.0,
    apiType: 'strength',
    aliases: ['butterfly', 'chest fly machine', 'pec fly', 'pecs'],
  },
  {
    id: 'cable-fly',
    name: 'Cable Chest Fly',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.CABLE,
    icon: 'barbell',
    description: 'Standing cable crossover',
    met: 4.0,
    apiType: 'strength',
    aliases: ['crossover', 'cable crossover', 'chest fly'],
  },
  {
    id: 'push-ups',
    name: 'Push-Ups',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Bodyweight chest and triceps press',
    met: 5.0,
    apiType: 'strength',
    aliases: ['pushup', 'press up', 'chest'],
  },
  {
    id: 'chest-dips',
    name: 'Chest Dips',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Parallel bar dips, forward lean',
    met: 6.0,
    apiType: 'strength',
    aliases: ['dips', 'parallel bars'],
  },
  {
    id: 'assisted-dip',
    name: 'Assisted Dip Machine',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Counterweighted dip station',
    met: 4.5,
    apiType: 'strength',
    aliases: ['gravitron', 'assisted dips'],
  },

  // ==========================================================================
  // STRENGTH — BACK (UPPER BODY PULL)
  // ==========================================================================
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.CABLE,
    icon: 'barbell',
    description: 'Wide-grip pulldown for lats',
    met: 4.5,
    apiType: 'strength',
    aliases: ['pulldown', 'lats', 'back'],
  },
  {
    id: 'close-grip-pulldown',
    name: 'Close-Grip Pulldown',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.CABLE,
    icon: 'barbell',
    description: 'Neutral-grip pulldown for lats and biceps',
    met: 4.5,
    apiType: 'strength',
    aliases: ['v bar pulldown', 'back'],
  },
  {
    id: 'straight-arm-pulldown',
    name: 'Straight-Arm Pulldown',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.CABLE,
    icon: 'barbell',
    description: 'Cable lat isolation with straight arms',
    met: 4.0,
    apiType: 'strength',
    aliases: ['lat pullover', 'lats'],
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.CABLE,
    icon: 'barbell',
    description: 'Low-pulley row for mid back',
    met: 4.5,
    apiType: 'strength',
    aliases: ['cable row', 'low row', 'back'],
  },
  {
    id: 'seated-row-machine',
    name: 'Seated Row Machine',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Chest-supported machine row',
    met: 4.5,
    apiType: 'strength',
    aliases: ['machine row', 'chest supported row', 'back'],
  },
  {
    id: 'barbell-row',
    name: 'Barbell Bent-Over Row',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'barbell',
    description: 'Hinged barbell row for back thickness',
    met: 5.0,
    apiType: 'strength',
    aliases: ['bent over row', 'bb row', 'back'],
  },
  {
    id: 'dumbbell-row',
    name: 'One-Arm Dumbbell Row',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.DUMBBELL,
    icon: 'barbell',
    description: 'Single-arm row braced on a bench',
    met: 5.0,
    apiType: 'strength',
    aliases: ['db row', 'single arm row', 'back'],
  },
  {
    id: 't-bar-row',
    name: 'T-Bar Row',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Landmine or T-bar station row',
    met: 5.0,
    apiType: 'strength',
    aliases: ['landmine row', 'back'],
  },
  {
    id: 'pull-ups',
    name: 'Pull-Ups',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Overhand bodyweight pull to the bar',
    met: 8.0,
    apiType: 'strength',
    aliases: ['pullup', 'chin bar', 'lats'],
  },
  {
    id: 'chin-ups',
    name: 'Chin-Ups',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Underhand pull-up for lats and biceps',
    met: 8.0,
    apiType: 'strength',
    aliases: ['chinup', 'underhand pullup'],
  },
  {
    id: 'assisted-pull-up',
    name: 'Assisted Pull-Up Machine',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Counterweighted pull-up station',
    met: 4.5,
    apiType: 'strength',
    aliases: ['gravitron', 'assisted pullup'],
  },
  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Fly Machine',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Reverse pec deck for rear shoulders',
    met: 4.0,
    apiType: 'strength',
    aliases: ['reverse pec deck', 'reverse fly', 'rear delts'],
  },
  {
    id: 'face-pull',
    name: 'Cable Face Pull',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.CABLE,
    icon: 'barbell',
    description: 'High cable pull for rear delts and traps',
    met: 4.0,
    apiType: 'strength',
    aliases: ['rope face pull', 'rear delts'],
  },
  {
    id: 'shrugs',
    name: 'Shrugs',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.DUMBBELL,
    icon: 'barbell',
    description: 'Dumbbell or barbell trap shrugs',
    met: 4.0,
    apiType: 'strength',
    aliases: ['traps', 'trap shrug'],
  },
  {
    id: 'back-extension',
    name: 'Back Extension',
    category: STRENGTH,
    muscleGroup: CORE,
    equipment: EQUIPMENT.MACHINE,
    icon: 'body',
    description: 'Hyperextension bench for lower back',
    met: 4.0,
    apiType: 'strength',
    aliases: ['hyperextension', 'lower back', 'roman chair'],
  },

  // ==========================================================================
  // STRENGTH — SHOULDERS
  // ==========================================================================
  {
    id: 'overhead-press',
    name: 'Barbell Overhead Press',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'barbell',
    description: 'Standing strict press for shoulders',
    met: 5.0,
    apiType: 'strength',
    aliases: ['military press', 'ohp', 'shoulder press', 'delts'],
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.DUMBBELL,
    icon: 'barbell',
    description: 'Seated or standing dumbbell press',
    met: 5.0,
    apiType: 'strength',
    aliases: ['db shoulder press', 'delts'],
  },
  {
    id: 'shoulder-press-machine',
    name: 'Shoulder Press Machine',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Seated machine overhead press',
    met: 4.5,
    apiType: 'strength',
    aliases: ['machine shoulder press', 'delts'],
  },
  {
    id: 'arnold-press',
    name: 'Arnold Press',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.DUMBBELL,
    icon: 'barbell',
    description: 'Rotating dumbbell overhead press',
    met: 5.0,
    apiType: 'strength',
    aliases: ['arnie press', 'delts'],
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.DUMBBELL,
    icon: 'barbell',
    description: 'Side raise for medial delts',
    met: 4.0,
    apiType: 'strength',
    aliases: ['side raise', 'lat raise', 'delts'],
  },
  {
    id: 'front-raise',
    name: 'Front Raise',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.DUMBBELL,
    icon: 'barbell',
    description: 'Forward raise for front delts',
    met: 4.0,
    apiType: 'strength',
    aliases: ['anterior delt raise', 'delts'],
  },
  {
    id: 'upright-row',
    name: 'Upright Row',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.CABLE,
    icon: 'barbell',
    description: 'Cable or barbell pull to the chin',
    met: 4.5,
    apiType: 'strength',
    aliases: ['delts', 'traps'],
  },

  // ==========================================================================
  // STRENGTH — ARMS
  // ==========================================================================
  {
    id: 'barbell-curl',
    name: 'Barbell Biceps Curl',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'barbell',
    description: 'Standing curl with straight or EZ bar',
    met: 4.0,
    apiType: 'strength',
    aliases: ['bicep curl', 'ez bar curl', 'biceps', 'arms'],
  },
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Biceps Curl',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.DUMBBELL,
    icon: 'barbell',
    description: 'Alternating or simultaneous curls',
    met: 4.0,
    apiType: 'strength',
    aliases: ['bicep curl', 'db curl', 'biceps', 'arms'],
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.DUMBBELL,
    icon: 'barbell',
    description: 'Neutral-grip curl for brachialis',
    met: 4.0,
    apiType: 'strength',
    aliases: ['neutral curl', 'biceps', 'forearms'],
  },
  {
    id: 'preacher-curl',
    name: 'Preacher Curl',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Arm-supported curl bench or machine',
    met: 4.0,
    apiType: 'strength',
    aliases: ['scott curl', 'biceps', 'arms'],
  },
  {
    id: 'cable-curl',
    name: 'Cable Biceps Curl',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.CABLE,
    icon: 'barbell',
    description: 'Low-pulley curl with constant tension',
    met: 4.0,
    apiType: 'strength',
    aliases: ['biceps', 'arms'],
  },
  {
    id: 'triceps-pushdown',
    name: 'Triceps Pushdown',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.CABLE,
    icon: 'barbell',
    description: 'Rope or bar cable pushdown',
    met: 4.0,
    apiType: 'strength',
    aliases: ['rope pushdown', 'tricep pushdown', 'triceps', 'arms'],
  },
  {
    id: 'triceps-extension-machine',
    name: 'Triceps Extension Machine',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Seated machine triceps extension',
    met: 4.0,
    apiType: 'strength',
    aliases: ['tricep machine', 'triceps', 'arms'],
  },
  {
    id: 'overhead-triceps-extension',
    name: 'Overhead Triceps Extension',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.DUMBBELL,
    icon: 'barbell',
    description: 'Dumbbell or rope extension behind the head',
    met: 4.0,
    apiType: 'strength',
    aliases: ['french press', 'triceps', 'arms'],
  },
  {
    id: 'skull-crushers',
    name: 'Skull Crushers',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'barbell',
    description: 'Lying triceps extension on a bench',
    met: 4.5,
    apiType: 'strength',
    aliases: ['lying triceps extension', 'triceps'],
  },
  {
    id: 'close-grip-bench',
    name: 'Close-Grip Bench Press',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'barbell',
    description: 'Narrow-grip press for triceps',
    met: 5.0,
    apiType: 'strength',
    aliases: ['cgbp', 'triceps'],
  },
  {
    id: 'bench-dips',
    name: 'Bench Dips',
    category: STRENGTH,
    muscleGroup: UPPER_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Triceps dips off a bench or box',
    met: 5.0,
    apiType: 'strength',
    aliases: ['tricep dips', 'triceps'],
  },

  // ==========================================================================
  // STRENGTH — LOWER BODY
  // ==========================================================================
  {
    id: 'leg-press',
    name: 'Leg Press',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Seated or 45° sled press',
    met: 5.0,
    apiType: 'strength',
    aliases: ['leg press machine', 'quads', 'legs'],
  },
  {
    id: 'hack-squat',
    name: 'Hack Squat Machine',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Angled sled squat machine',
    met: 5.5,
    apiType: 'strength',
    aliases: ['hack squat', 'quads', 'legs'],
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Seated quad isolation machine',
    met: 4.0,
    apiType: 'strength',
    aliases: ['quad extension', 'knee extension', 'quads'],
  },
  {
    id: 'seated-leg-curl',
    name: 'Seated Leg Curl',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Seated hamstring curl machine',
    met: 4.0,
    apiType: 'strength',
    aliases: ['hamstring curl', 'hamstrings', 'legs'],
  },
  {
    id: 'lying-leg-curl',
    name: 'Lying Leg Curl',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Prone hamstring curl machine',
    met: 4.0,
    apiType: 'strength',
    aliases: ['hamstring curl', 'prone curl', 'hamstrings'],
  },
  {
    id: 'barbell-squat',
    name: 'Barbell Back Squat',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'barbell',
    description: 'Back-loaded squat from the rack',
    met: 6.0,
    apiType: 'strength',
    aliases: ['squat', 'back squat', 'legs', 'quads'],
  },
  {
    id: 'front-squat',
    name: 'Barbell Front Squat',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'barbell',
    description: 'Front-racked squat for quads and core',
    met: 6.0,
    apiType: 'strength',
    aliases: ['squat', 'quads'],
  },
  {
    id: 'smith-squat',
    name: 'Smith Machine Squat',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.SMITH,
    icon: 'barbell',
    description: 'Guided bar squat',
    met: 5.0,
    apiType: 'strength',
    aliases: ['smith squat', 'legs'],
  },
  {
    id: 'goblet-squat',
    name: 'Goblet Squat',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.DUMBBELL,
    icon: 'barbell',
    description: 'Squat holding a dumbbell at the chest',
    met: 5.0,
    apiType: 'strength',
    aliases: ['squat', 'legs'],
  },
  {
    id: 'bodyweight-squat',
    name: 'Bodyweight Squats',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Unweighted squats for reps',
    met: 4.0,
    apiType: 'strength',
    aliases: ['air squat', 'squat', 'legs'],
  },
  {
    id: 'lunges',
    name: 'Walking Lunges',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Alternating forward lunges',
    met: 4.5,
    apiType: 'strength',
    aliases: ['lunge', 'legs', 'glutes'],
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.DUMBBELL,
    icon: 'body',
    description: 'Rear-foot-elevated single leg squat',
    met: 5.0,
    apiType: 'strength',
    aliases: ['split squat', 'rfess', 'legs'],
  },
  {
    id: 'step-ups',
    name: 'Step-Ups',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.DUMBBELL,
    icon: 'trending-up',
    description: 'Weighted step onto a box or bench',
    met: 5.0,
    apiType: 'strength',
    aliases: ['box step up', 'glutes', 'legs'],
  },
  {
    id: 'deadlift',
    name: 'Barbell Deadlift',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'barbell',
    description: 'Conventional pull from the floor',
    met: 6.0,
    apiType: 'strength',
    aliases: ['dead lift', 'pull', 'posterior chain'],
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'barbell',
    description: 'Hip hinge for hamstrings and glutes',
    met: 5.5,
    apiType: 'strength',
    aliases: ['rdl', 'stiff leg deadlift', 'hamstrings'],
  },
  {
    id: 'sumo-deadlift',
    name: 'Sumo Deadlift',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'barbell',
    description: 'Wide-stance pull from the floor',
    met: 6.0,
    apiType: 'strength',
    aliases: ['dead lift', 'sumo'],
  },
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'barbell',
    description: 'Bench-supported barbell glute bridge',
    met: 5.0,
    apiType: 'strength',
    aliases: ['glute bridge', 'glutes', 'booty'],
  },
  {
    id: 'glute-kickback',
    name: 'Glute Kickback Machine',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Cable or machine hip extension',
    met: 4.0,
    apiType: 'strength',
    aliases: ['cable kickback', 'glutes'],
  },
  {
    id: 'hip-abduction',
    name: 'Hip Abduction Machine',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Seated outer-thigh and glute medius work',
    met: 4.0,
    apiType: 'strength',
    aliases: ['outer thigh', 'abductor', 'glutes'],
  },
  {
    id: 'hip-adduction',
    name: 'Hip Adduction Machine',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Seated inner-thigh machine',
    met: 4.0,
    apiType: 'strength',
    aliases: ['inner thigh', 'adductor'],
  },
  {
    id: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Loaded calf raise machine',
    met: 4.0,
    apiType: 'strength',
    aliases: ['calf raise', 'calves'],
  },
  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Seated soleus calf machine',
    met: 4.0,
    apiType: 'strength',
    aliases: ['calf raise', 'calves'],
  },

  // ==========================================================================
  // CORE
  // ==========================================================================
  {
    id: 'plank',
    name: 'Plank',
    category: STRENGTH,
    muscleGroup: CORE,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Front isometric hold',
    met: 3.5,
    apiType: 'strength',
    aliases: ['front plank', 'abs', 'core'],
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    category: STRENGTH,
    muscleGroup: CORE,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Lateral isometric hold for obliques',
    met: 3.5,
    apiType: 'strength',
    aliases: ['obliques', 'abs', 'core'],
  },
  {
    id: 'crunches',
    name: 'Crunches',
    category: STRENGTH,
    muscleGroup: CORE,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Floor crunches for upper abs',
    met: 3.5,
    apiType: 'strength',
    aliases: ['abs', 'core'],
  },
  {
    id: 'sit-ups',
    name: 'Sit-Ups',
    category: STRENGTH,
    muscleGroup: CORE,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Full range sit-ups',
    met: 4.0,
    apiType: 'strength',
    aliases: ['situp', 'abs', 'core'],
  },
  {
    id: 'ab-crunch-machine',
    name: 'Ab Crunch Machine',
    category: STRENGTH,
    muscleGroup: CORE,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Seated weighted crunch machine',
    met: 4.0,
    apiType: 'strength',
    aliases: ['abdominal machine', 'abs', 'core'],
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    category: STRENGTH,
    muscleGroup: CORE,
    equipment: EQUIPMENT.CABLE,
    icon: 'barbell',
    description: 'Kneeling rope crunch',
    met: 4.0,
    apiType: 'strength',
    aliases: ['rope crunch', 'abs', 'core'],
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    category: STRENGTH,
    muscleGroup: CORE,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Leg raise hanging from a bar',
    met: 4.5,
    apiType: 'strength',
    aliases: ['knee raise', 'abs', 'core'],
  },
  {
    id: 'captains-chair',
    name: "Captain's Chair Leg Raise",
    category: STRENGTH,
    muscleGroup: CORE,
    equipment: EQUIPMENT.MACHINE,
    icon: 'barbell',
    description: 'Supported knee raise station',
    met: 4.0,
    apiType: 'strength',
    aliases: ['vertical knee raise', 'abs', 'core'],
  },
  {
    id: 'lying-leg-raise',
    name: 'Lying Leg Raise',
    category: STRENGTH,
    muscleGroup: CORE,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Floor leg raise for lower abs',
    met: 4.0,
    apiType: 'strength',
    aliases: ['leg lifts', 'abs', 'core'],
  },
  {
    id: 'russian-twist',
    name: 'Russian Twist',
    category: STRENGTH,
    muscleGroup: CORE,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Seated rotation for obliques',
    met: 4.0,
    apiType: 'strength',
    aliases: ['obliques', 'twist', 'core'],
  },
  {
    id: 'bicycle-crunch',
    name: 'Bicycle Crunch',
    category: STRENGTH,
    muscleGroup: CORE,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Alternating elbow-to-knee crunch',
    met: 4.5,
    apiType: 'strength',
    aliases: ['abs', 'obliques', 'core'],
  },
  {
    id: 'dead-bug',
    name: 'Dead Bug',
    category: STRENGTH,
    muscleGroup: CORE,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Supine anti-extension core drill',
    met: 3.5,
    apiType: 'strength',
    aliases: ['core stability', 'abs'],
  },
  {
    id: 'ab-rollout',
    name: 'Ab Wheel Rollout',
    category: STRENGTH,
    muscleGroup: CORE,
    equipment: EQUIPMENT.OTHER,
    icon: 'body',
    description: 'Ab wheel or barbell rollout',
    met: 4.5,
    apiType: 'strength',
    aliases: ['ab wheel', 'rollout', 'abs'],
  },
  {
    id: 'mountain-climbers',
    name: 'Mountain Climbers',
    category: STRENGTH,
    muscleGroup: CORE,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'flash',
    description: 'Plank position knee drives',
    met: 8.0,
    apiType: 'hiit',
    aliases: ['abs', 'core', 'cardio core'],
  },

  // ==========================================================================
  // FULL BODY & FUNCTIONAL
  // ==========================================================================
  {
    id: 'weight-lifting',
    name: 'Weight Lifting (General)',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'barbell',
    description: 'General free-weight session',
    met: 5.0,
    apiType: 'strength',
    aliases: ['weights', 'lifting', 'gym session', 'resistance training'],
  },
  {
    id: 'bodyweight',
    name: 'Bodyweight Training',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Push-ups, pull-ups, squats',
    met: 6.0,
    apiType: 'strength',
    aliases: ['calisthenics', 'no equipment'],
  },
  {
    id: 'crossfit',
    name: 'CrossFit',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'fitness',
    description: 'High-intensity functional training',
    met: 11.0,
    apiType: 'hiit',
    aliases: ['wod', 'functional fitness'],
  },
  {
    id: 'circuit-training',
    name: 'Circuit Training',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.MACHINE,
    icon: 'repeat',
    description: 'Machine or free-weight circuit',
    met: 7.5,
    apiType: 'hiit',
    aliases: ['30 minute circuit', 'express circuit', 'super circuit'],
  },
  {
    id: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.KETTLEBELL,
    icon: 'fitness',
    description: 'Explosive hip hinge swing',
    met: 9.8,
    apiType: 'hiit',
    aliases: ['kb swing', 'kettle bell'],
  },
  {
    id: 'burpees',
    name: 'Burpees',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'flash',
    description: 'Squat thrust into a jump',
    met: 8.0,
    apiType: 'hiit',
    aliases: ['squat thrust'],
  },
  {
    id: 'thrusters',
    name: 'Thrusters',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'flash',
    description: 'Front squat into overhead press',
    met: 8.0,
    apiType: 'hiit',
    aliases: ['squat to press'],
  },
  {
    id: 'clean-and-press',
    name: 'Clean and Press',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BARBELL,
    icon: 'barbell',
    description: 'Floor-to-overhead olympic lift',
    met: 6.0,
    apiType: 'strength',
    aliases: ['power clean', 'olympic lift'],
  },
  {
    id: 'farmers-carry',
    name: "Farmer's Carry",
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.DUMBBELL,
    icon: 'fitness',
    description: 'Loaded carry for grip and core',
    met: 5.0,
    apiType: 'strength',
    aliases: ['loaded carry', 'suitcase carry', 'grip'],
  },
  {
    id: 'battle-ropes',
    name: 'Battle Ropes',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'flash',
    description: 'Rope waves and slams',
    met: 8.0,
    apiType: 'hiit',
    aliases: ['ropes', 'rope waves'],
  },
  {
    id: 'sled-push',
    name: 'Sled Push',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'flash',
    description: 'Prowler or turf sled drive',
    met: 9.0,
    apiType: 'hiit',
    aliases: ['prowler', 'sled drag', 'turf'],
  },
  {
    id: 'box-jumps',
    name: 'Box Jumps',
    category: STRENGTH,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'flash',
    description: 'Explosive jump onto a box',
    met: 8.0,
    apiType: 'hiit',
    aliases: ['plyometrics', 'jump training'],
  },
  {
    id: 'med-ball-slam',
    name: 'Medicine Ball Slams',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'flash',
    description: 'Overhead slam with a medicine ball',
    met: 7.0,
    apiType: 'hiit',
    aliases: ['med ball', 'slam ball', 'wall ball'],
  },
  {
    id: 'trx',
    name: 'Suspension Training (TRX)',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'body',
    description: 'Strap-based bodyweight training',
    met: 5.0,
    apiType: 'strength',
    aliases: ['trx', 'straps', 'suspension'],
  },
  {
    id: 'bear-crawl',
    name: 'Bear Crawl',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'body',
    description: 'Quadruped crawl for core and shoulders',
    met: 6.0,
    apiType: 'strength',
    aliases: ['crawl', 'animal flow'],
  },
  {
    id: 'turkish-get-up',
    name: 'Turkish Get-Up',
    category: STRENGTH,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.KETTLEBELL,
    icon: 'fitness',
    description: 'Floor-to-standing loaded carry pattern',
    met: 5.0,
    apiType: 'strength',
    aliases: ['tgu', 'get up'],
  },

  // ==========================================================================
  // YOGA & FLEXIBILITY
  // ==========================================================================
  {
    id: 'vinyasa-yoga',
    name: 'Vinyasa Yoga',
    category: YOGA,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'flower',
    description: 'Flow-based dynamic yoga',
    met: 4.0,
    apiType: 'yoga',
    aliases: ['flow yoga'],
  },
  {
    id: 'power-yoga',
    name: 'Power Yoga',
    category: YOGA,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'flame',
    description: 'Intense, fitness-focused yoga',
    met: 5.0,
    apiType: 'yoga',
    aliases: ['ashtanga'],
  },
  {
    id: 'hatha-yoga',
    name: 'Hatha Yoga',
    category: YOGA,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'leaf',
    description: 'Gentle, alignment-focused yoga',
    met: 2.5,
    apiType: 'yoga',
    aliases: ['gentle yoga'],
  },
  {
    id: 'yin-yoga',
    name: 'Yin Yoga',
    category: YOGA,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'moon',
    description: 'Slow-paced, meditative yoga',
    met: 2.5,
    apiType: 'yoga',
    aliases: ['restorative yoga'],
  },
  {
    id: 'hot-yoga',
    name: 'Hot Yoga',
    category: YOGA,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'sunny',
    description: 'Yoga in a heated room',
    met: 5.0,
    apiType: 'yoga',
    aliases: ['bikram'],
  },
  {
    id: 'pilates',
    name: 'Pilates',
    category: FLEXIBILITY,
    muscleGroup: CORE,
    equipment: EQUIPMENT.OTHER,
    icon: 'heart',
    description: 'Core-focused mat or reformer',
    met: 3.0,
    apiType: 'flexibility',
    aliases: ['reformer', 'mat pilates', 'core'],
  },
  {
    id: 'stretching',
    name: 'Stretching',
    category: FLEXIBILITY,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'expand',
    description: 'General flexibility work',
    met: 2.5,
    apiType: 'flexibility',
    aliases: ['mobility', 'cooldown', 'warm up'],
  },
  {
    id: 'foam-rolling',
    name: 'Foam Rolling',
    category: FLEXIBILITY,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'expand',
    description: 'Self-myofascial release',
    met: 2.5,
    apiType: 'flexibility',
    aliases: ['myofascial', 'recovery', 'roller'],
  },

  // ==========================================================================
  // WALKING
  // ==========================================================================
  {
    id: 'walking-slow',
    name: 'Walking (Slow)',
    category: WALKING,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'walk',
    description: '2-3 mph casual walk',
    met: 2.5,
    apiType: 'walking',
    aliases: ['stroll'],
  },
  {
    id: 'walking-moderate',
    name: 'Walking (Moderate)',
    category: WALKING,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'walk',
    description: '3-4 mph brisk walk',
    met: 3.5,
    apiType: 'walking',
    aliases: ['brisk walk'],
  },
  {
    id: 'walking-fast',
    name: 'Walking (Fast)',
    category: WALKING,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'walk',
    description: '4.5+ mph power walk',
    met: 5.0,
    apiType: 'walking',
    aliases: ['power walk', 'speed walk'],
  },
  {
    id: 'hiking',
    name: 'Hiking',
    category: WALKING,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'trail-sign',
    description: 'Trail hiking with elevation',
    met: 6.0,
    apiType: 'hiking',
    aliases: ['trail', 'trek'],
  },

  // ==========================================================================
  // CYCLING
  // ==========================================================================
  {
    id: 'cycling-leisure',
    name: 'Cycling (Leisure)',
    category: CYCLING,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'bicycle',
    description: 'Casual bike riding',
    met: 4.0,
    apiType: 'cycling',
    aliases: ['bike ride'],
  },
  {
    id: 'cycling-moderate',
    name: 'Cycling (Moderate)',
    category: CYCLING,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'bicycle',
    description: '12-14 mph moderate pace',
    met: 8.0,
    apiType: 'cycling',
    aliases: ['bike ride'],
  },
  {
    id: 'cycling-vigorous',
    name: 'Cycling (Vigorous)',
    category: CYCLING,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'bicycle',
    description: '16+ mph racing pace',
    met: 12.0,
    apiType: 'cycling',
    aliases: ['road cycling', 'race'],
  },
  {
    id: 'stationary-bike',
    name: 'Stationary Bike',
    category: CYCLING,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.CARDIO_MACHINE,
    icon: 'bicycle',
    description: 'Upright exercise bike, moderate effort',
    met: 7.0,
    apiType: 'cycling',
    aliases: ['exercise bike', 'upright bike', 'indoor bike'],
  },
  {
    id: 'recumbent-bike',
    name: 'Recumbent Bike',
    category: CYCLING,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.CARDIO_MACHINE,
    icon: 'bicycle',
    description: 'Seated-back exercise bike',
    met: 5.0,
    apiType: 'cycling',
    aliases: ['seated bike', 'exercise bike'],
  },
  {
    id: 'spin-class',
    name: 'Spin Class',
    category: CYCLING,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.CARDIO_MACHINE,
    icon: 'bicycle',
    description: 'Indoor cycling class',
    met: 11.0,
    apiType: 'cycling',
    aliases: ['spinning', 'cycle class', 'peloton'],
  },
  {
    id: 'mountain-biking',
    name: 'Mountain Biking',
    category: CYCLING,
    muscleGroup: LOWER_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'bicycle',
    description: 'Off-road trail biking',
    met: 8.5,
    apiType: 'cycling',
    aliases: ['mtb', 'trail bike'],
  },

  // ==========================================================================
  // SWIMMING
  // ==========================================================================
  {
    id: 'swimming-leisure',
    name: 'Swimming (Leisure)',
    category: SWIMMING,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'water',
    description: 'Casual swimming',
    met: 6.0,
    apiType: 'swimming',
    aliases: ['pool'],
  },
  {
    id: 'swimming-laps',
    name: 'Swimming Laps',
    category: SWIMMING,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'water',
    description: 'Freestyle lap swimming',
    met: 10.0,
    apiType: 'swimming',
    aliases: ['lengths', 'freestyle', 'front crawl'],
  },
  {
    id: 'water-aerobics',
    name: 'Water Aerobics',
    category: SWIMMING,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'water',
    description: 'Pool-based cardio class',
    met: 5.0,
    apiType: 'swimming',
    aliases: ['aqua aerobics', 'aqua fit'],
  },

  // ==========================================================================
  // SPORTS
  // ==========================================================================
  {
    id: 'basketball',
    name: 'Basketball',
    category: SPORTS,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'basketball',
    description: 'Pickup game or practice',
    met: 8.5,
    apiType: 'sports',
    aliases: ['hoops'],
  },
  {
    id: 'soccer',
    name: 'Soccer',
    category: SPORTS,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'football',
    description: 'Soccer game or practice',
    met: 10.0,
    apiType: 'sports',
    aliases: ['football', 'futbol'],
  },
  {
    id: 'tennis',
    name: 'Tennis',
    category: SPORTS,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'tennisball',
    description: 'Singles or doubles tennis',
    met: 7.0,
    apiType: 'sports',
    aliases: ['racquet'],
  },
  {
    id: 'pickleball',
    name: 'Pickleball',
    category: SPORTS,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'tennisball',
    description: 'Doubles or singles pickleball',
    met: 6.0,
    apiType: 'sports',
    aliases: ['paddle', 'padel'],
  },
  {
    id: 'volleyball',
    name: 'Volleyball',
    category: SPORTS,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'american-football',
    description: 'Beach or indoor volleyball',
    met: 5.0,
    apiType: 'sports',
    aliases: [],
  },
  {
    id: 'golf',
    name: 'Golf',
    category: SPORTS,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'golf',
    description: 'Walking course, carrying clubs',
    met: 4.0,
    apiType: 'sports',
    aliases: [],
  },
  {
    id: 'martial-arts',
    name: 'Martial Arts',
    category: SPORTS,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'hand-right',
    description: 'Karate, taekwondo, judo, etc.',
    met: 11.0,
    apiType: 'sports',
    aliases: ['karate', 'jiu jitsu', 'bjj', 'mma', 'judo'],
  },
  {
    id: 'boxing',
    name: 'Boxing',
    category: SPORTS,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.OTHER,
    icon: 'hand-right',
    description: 'Boxing training or sparring',
    met: 12.0,
    apiType: 'sports',
    aliases: ['heavy bag', 'kickboxing', 'sparring'],
  },
  {
    id: 'dancing',
    name: 'Dancing',
    category: SPORTS,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'musical-notes',
    description: 'Social or aerobic dancing',
    met: 5.0,
    apiType: 'dancing',
    aliases: ['dance'],
  },
  {
    id: 'zumba',
    name: 'Zumba',
    category: SPORTS,
    muscleGroup: FULL_BODY,
    equipment: EQUIPMENT.BODYWEIGHT,
    icon: 'musical-notes',
    description: 'Latin-inspired dance fitness',
    met: 7.0,
    apiType: 'dancing',
    aliases: ['dance fitness', 'dance cardio'],
  },
];

/** Reference weight the card estimate is quoted for */
const REFERENCE_WEIGHT_KG = 70;

/**
 * Mirror of backend/src/services/metCalorieService.js MET_VALUES.
 *
 * The API is the source of truth for logged calories — it recomputes them from
 * `apiType` + intensity — so estimates shown here use the same table. The
 * per-exercise `met` above stays as the Compendium reference for when the API
 * starts accepting an exercise-level MET.
 */
const BACKEND_MET_VALUES = {
  running: { LIGHT: 6.0, MODERATE: 10.0, VIGOROUS: 14.0 },
  cycling: { LIGHT: 4.0, MODERATE: 8.0, VIGOROUS: 12.0 },
  walking: { LIGHT: 2.5, MODERATE: 3.5, VIGOROUS: 5.0 },
  gym: { LIGHT: 3.5, MODERATE: 5.0, VIGOROUS: 6.0 },
  swimming: { LIGHT: 4.5, MODERATE: 7.0, VIGOROUS: 10.0 },
  yoga: { LIGHT: 2.5, MODERATE: 4.0, VIGOROUS: 5.0 },
  sports: { LIGHT: 4.0, MODERATE: 6.0, VIGOROUS: 8.0 },
  hiking: { LIGHT: 4.5, MODERATE: 6.0, VIGOROUS: 8.0 },
  dancing: { LIGHT: 3.0, MODERATE: 5.0, VIGOROUS: 7.0 },
  hiit: { LIGHT: 5.0, MODERATE: 8.0, VIGOROUS: 12.0 },
  strength: { LIGHT: 3.0, MODERATE: 5.0, VIGOROUS: 6.0 },
  cardio: { LIGHT: 4.0, MODERATE: 7.0, VIGOROUS: 10.0 },
  flexibility: { LIGHT: 2.0, MODERATE: 2.5, VIGOROUS: 3.0 },
  general: { LIGHT: 3.0, MODERATE: 5.0, VIGOROUS: 7.0 },
};

/** MET the API will actually bill this exercise at */
const getLoggedMet = (exercise, intensityKey = 'MODERATE') => {
  const row = BACKEND_MET_VALUES[exercise.apiType] || BACKEND_MET_VALUES.general;
  return row[intensityKey] || row.MODERATE;
};

export const EXERCISES = RAW_EXERCISES.map((exercise) => ({
  aliases: [],
  ...exercise,
  caloriesPer30Min: Math.round(getLoggedMet(exercise) * REFERENCE_WEIGHT_KG * 0.5),
}));

/**
 * Focus filters shown as a second chip row. The first four are muscle groups;
 * "Machines" cuts across them for anyone working the machine circuit.
 */
export const FOCUS_FILTERS = [
  { key: 'upper', label: MUSCLE_GROUPS.UPPER_BODY, match: (ex) => ex.muscleGroup === MUSCLE_GROUPS.UPPER_BODY },
  { key: 'lower', label: MUSCLE_GROUPS.LOWER_BODY, match: (ex) => ex.muscleGroup === MUSCLE_GROUPS.LOWER_BODY },
  { key: 'core', label: MUSCLE_GROUPS.CORE, match: (ex) => ex.muscleGroup === MUSCLE_GROUPS.CORE },
  { key: 'full', label: MUSCLE_GROUPS.FULL_BODY, match: (ex) => ex.muscleGroup === MUSCLE_GROUPS.FULL_BODY },
  { key: 'machines', label: 'Machines', match: (ex) => MACHINE_EQUIPMENT.has(ex.equipment) },
  { key: 'free-weights', label: 'Free Weights', match: (ex) => ex.equipment === EQUIPMENT.BARBELL || ex.equipment === EQUIPMENT.DUMBBELL || ex.equipment === EQUIPMENT.KETTLEBELL },
  { key: 'bodyweight', label: 'Bodyweight', match: (ex) => ex.equipment === EQUIPMENT.BODYWEIGHT },
];

/**
 * Calculate calories burned based on duration, weight and intensity.
 * Formula: Calories = MET × weight(kg) × time(hours)
 *
 * Uses the same MET table the API logs with, so the preview in the modal and
 * the number that lands on the activity card agree.
 */
export const calculateCalories = (exercise, durationMinutes, weightKg = REFERENCE_WEIGHT_KG, intensityLevel = 'MODERATE') => {
  const met = getLoggedMet(exercise, INTENSITY_LEVELS[intensityLevel] ? intensityLevel : 'MODERATE');
  const hours = durationMinutes / 60;
  return Math.round(met * weightKg * hours);
};

/**
 * Get exercises by category
 */
export const getExercisesByCategory = (category) => {
  return EXERCISES.filter((ex) => ex.category === category);
};

/**
 * Get exercises by muscle group
 */
export const getExercisesByMuscleGroup = (muscleGroup) => {
  return EXERCISES.filter((ex) => ex.muscleGroup === muscleGroup);
};

/** Everything a query can match against, lowercased once per exercise */
const searchIndex = new Map(
  EXERCISES.map((ex) => [
    ex.id,
    [ex.name, ex.description, ex.muscleGroup, ex.equipment, ...(ex.aliases || [])]
      .join(' ')
      .toLowerCase(),
  ])
);

/** Levenshtein distance, capped early — used only for the typo fallback */
const editDistance = (a, b, max) => {
  if (Math.abs(a.length - b.length) > max) return max + 1;
  let prev = Array.from({ length: b.length + 1 }, (_, i) => i);
  for (let i = 1; i <= a.length; i += 1) {
    const row = [i];
    let rowMin = i;
    for (let j = 1; j <= b.length; j += 1) {
      const cost = a[i - 1] === b[j - 1] ? 0 : 1;
      row[j] = Math.min(prev[j] + 1, row[j - 1] + 1, prev[j - 1] + cost);
      rowMin = Math.min(rowMin, row[j]);
    }
    if (rowMin > max) return max + 1;
    prev = row;
  }
  return prev[b.length];
};

/** How much slack a typo gets, by word length */
const typoTolerance = (word) => (word.length >= 8 ? 2 : word.length >= 5 ? 1 : 0);

/**
 * Search exercises by name, description, muscle group, equipment or alias.
 * Falls back to fuzzy word matching so "threadmill" still finds the treadmill.
 */
export const searchExercises = (query) => {
  const trimmed = (query || '').trim().toLowerCase();
  if (!trimmed) return EXERCISES;

  const exact = EXERCISES.filter((ex) => searchIndex.get(ex.id).includes(trimmed));
  if (exact.length > 0) return exact;

  const queryWords = trimmed.split(/\s+/).filter(Boolean);
  return EXERCISES.filter((ex) => {
    const words = searchIndex.get(ex.id).split(/[^a-z0-9]+/).filter(Boolean);
    return queryWords.every((qw) => {
      const tolerance = typoTolerance(qw);
      if (tolerance === 0) return words.some((w) => w.startsWith(qw));
      return words.some((w) => editDistance(qw, w, tolerance) <= tolerance);
    });
  });
};

/**
 * Combined filter used by the Activity screen: free-text query, modality
 * category and focus (muscle group / equipment) chips.
 */
export const filterExercises = ({ query, category, focusKey } = {}) => {
  let results = query ? searchExercises(query) : EXERCISES;

  if (category) {
    results = results.filter((ex) => ex.category === category);
  }

  if (focusKey) {
    const focus = FOCUS_FILTERS.find((f) => f.key === focusKey);
    if (focus) results = results.filter(focus.match);
  }

  return results;
};

/**
 * Get exercise by ID
 */
export const getExerciseById = (id) => {
  return EXERCISES.find((ex) => ex.id === id);
};

export default {
  EXERCISES,
  EXERCISE_CATEGORIES,
  MUSCLE_GROUPS,
  EQUIPMENT,
  FOCUS_FILTERS,
  INTENSITY_LEVELS,
  calculateCalories,
  filterExercises,
  searchExercises,
  getExercisesByCategory,
  getExercisesByMuscleGroup,
  getExerciseById,
};
